query_estabelecimento = 'SELECT CD_EMPRESA, CD_ESTABELECIMENTO, NM_FANTASIA_ESTAB FROM TASY.VW_EXIMIO_ESTABELECIMENTO'

query_empresa = 'SELECT CD_EMPRESA, NM_RAZAO_SOCIAL, DS_NOME_CURTO FROM TASY.VW_EXIMIO_EMPRESA'

query_ped_ex_ext_item = 'SELECT NR_PROC_INTERNO, NR_SEQ_PEDIDO FROM TASY.VW_EXIMIO_PED_EX_EXT_IT'

query_ped_ex_ext = "SELECT NR_SEQUENCIA, PEDIDO_EXAME_EXTERNO.NR_ATENDIMENTO, DT_INATIVACAO FROM TASY.VW_EXIMIO_PED_EX_EXT WHERE DT_INATIVACAO >= TO_DATE('{data_ini}', 'DD/MM/YYYY') AND DT_INATIVACAO < TO_DATE('{data_fim}', 'DD/MM/YYYY') + INTERVAL '1' DAY"

query_exame_lab = 'SELECT NR_SEQ_EXAME, NR_SEQ_GRUPO, NM_EXAME, DS_UNIDADE_MEDIDA FROM TASY.VW_EXIMIO_EXAME_LABORATORIO'

query_prescr_procedimento = 'SELECT IE_STATUS_ATEND, NR_SEQ_EXAME, NR_PRESCRICAO, CD_PROCEDIMENTO, IE_ORIGEM_PROCED, NR_SEQUENCIA, IE_VIA_APLICACAO, DS_HORARIOS, PRESCR_PROCEDIMENTO.DS_JUSTIFICATIVA FROM TASY.VW_EXIMIO_PRESCR_PROCEDIMENTO'

query_prescr_medica_v = 'SELECT NR_PRESCRICAO, NR_ATENDIMENTO FROM TASY.VW_EXIMIO_PRESCR_MEDICA_V'

query_diagnostico_doenca = 'SELECT CD_DOENCA, NR_ATENDIMENTO, NR_SEQ_INTERNO FROM TASY.VW_EXIMIO_DIAGNOSTICO_DOENCA'

query_atendimento_paciente = "SELECT NR_ATENDIMENTO, NR_ATENDIMENTO_MAE, DT_ENTRADA, DT_INICIO_ATENDIMENTO, DT_ATEND_MEDICO, DT_ALTA, DT_ALTA_MEDICO, DT_FIM_TRIAGEM, NR_SEQ_TRIAGEM, DT_MEDICACAO, CD_MOTIVO_ALTA, CD_MOTIVO_ALTA_MEDICA, IE_TIPO_ATENDIMENTO, CD_PESSOA_FISICA, CD_MEDICO_RESP, NR_SEQ_PAC_SENHA_FILA, IE_CLINICA FROM TASY.VW_EXIMIO_ATENDIMENTO_PACIENTE WHERE DT_ENTRADA >= TO_DATE('{data_ini}', 'DD/MM/YYYY') AND DT_ENTRADA < TO_DATE('{data_fim}', 'DD/MM/YYYY') + INTERVAL '1' DAY"

query_atend_paciente_unidade = "SELECT ATEND_PACIENTE_UNIDADE.NR_ATENDIMENTO, CD_SETOR_ATENDIMENTO, NR_SEQ_INTERNO, DT_ENTRADA_UNIDADE, DT_SAIDA_UNIDADE FROM TASY.VW_EXIMIO_ATEND_PAC_UNID WHERE DT_ENTRADA_UNIDADE >= TO_DATE('{data_ini}', 'DD/MM/YYYY') AND DT_ENTRADA_UNIDADE < TO_DATE('{data_fim}', 'DD/MM/YYYY') + INTERVAL '1' DAY"

query_setor_atendimento = 'SELECT DISTINCT SETOR_ATENDIMENTO.CD_SETOR_ATENDIMENTO, DS_SETOR_ATENDIMENTO, CD_CLASSIF_SETOR FROM TASY.VW_EXIMIO_SETOR_ATENDIMENTO'

query_atend_categoria_convenio = "SELECT ATEND_CATEGORIA_CONVENIO.NR_ATENDIMENTO, CD_CONVENIO, NR_SEQ_INTERNO, CD_CATEGORIA, DT_INICIO_VIGENCIA FROM TASY.VW_EXIMIO_ATEND_CATEG_CONVENIO WHERE DT_INICIO_VIGENCIA >= TO_DATE('{data_ini}', 'DD/MM/YYYY') AND DT_INICIO_VIGENCIA < TO_DATE('{data_fim}', 'DD/MM/YYYY') + INTERVAL '1' DAY"

query_convenio = 'SELECT DISTINCT CD_CONVENIO, DS_CONVENIO FROM TASY.VW_EXIMIO_CONVENIO'

query_categoria_convenio = 'SELECT DISTINCT CD_CONVENIO, CD_CATEGORIA FROM TASY.VW_EXIMIO_CATEGORIA_CONVENIO'

query_pessoa_fisica_medico = "SELECT DISTINCT PESSOA_FISICA.CD_PESSOA_FISICA, IE_SEXO, DT_CADASTRO_ORIGINAL, NM_PESSOA_PESQUISA FROM TASY.VW_EXIMIO_PESSOA_FISICA_MEDICO WHERE DT_CADASTRO_ORIGINAL >= TO_DATE('{data_ini}', 'DD/MM/YYYY') AND DT_CADASTRO_ORIGINAL < TO_DATE('{data_fim}', 'DD/MM/YYYY') + INTERVAL '1' DAY"

query_pessoa_fisica_pac = "SELECT DISTINCT PESSOA_FISICA.CD_PESSOA_FISICA, DT_NASCIMENTO, IE_SEXO, DT_CADASTRO_ORIGINAL FROM TASY.VW_EXIMIO_PESSOA_FISICA_PAC WHERE DT_CADASTRO_ORIGINAL >= TO_DATE('{data_ini}', 'DD/MM/YYYY') AND DT_CADASTRO_ORIGINAL < TO_DATE('{data_fim}', 'DD/MM/YYYY') + INTERVAL '1' DAY"

query_pac_senha_fila = "SELECT DT_INICIO_ATENDIMENTO, DT_GERACAO_SENHA, DT_FIM_ATENDIMENTO, NR_SEQ_FILA_SENHA, PACIENTE_SENHA_FILA.NR_SEQUENCIA FROM TASY.VW_EXIMIO_PAC_SENHA_FILA WHERE DT_INICIO_ATENDIMENTO >= TO_DATE('{data_ini}', 'DD/MM/YYYY') AND DT_INICIO_ATENDIMENTO < TO_DATE('{data_fim}', 'DD/MM/YYYY') + INTERVAL '1' DAY"

query_motivo_alta = 'SELECT CD_MOTIVO_ALTA, DS_MOTIVO_ALTA FROM TASY.VW_EXIMIO_MOTIVO_ALTA'

query_valor_dominio = 'SELECT CD_DOMINIO, VL_DOMINIO, DS_VALOR_DOMINIO FROM TASY.VW_EXIMIO_VALOR_DOMINIO'

query_cid_doenca = 'SELECT CD_DOENCA_CID, DS_DOENCA_CID FROM TASY.VW_EXIMIO_CID_DOENCA'

query_triagem_classif_risco = 'SELECT NR_SEQUENCIA, DS_CLASSIFICACAO FROM TASY.VW_EXIMIO_TRIAGEM_CLASSIF_RISCO'

query_medico_especialidade = 'SELECT CD_PESSOA_FISICA, CD_ESPECIALIDADE FROM TASY.VW_EXIMIO_MEDICO_ESPECIALIDADE'

query_especialidade_medica = 'SELECT CD_ESPECIALIDADE, DS_ESPECIALIDADE FROM TASY.VW_EXIMIO_ESPECIALIDADE_MEDICA'