query_estabelecimento_hdata = 'SELECT CD_EMPRESA, CD_ESTABELECIMENTO, NM_FANTASIA_ESTAB FROM UNIMED_GYN.ESTABELECIMENTO'

query_empresa_hdata = 'SELECT CD_EMPRESA, NM_RAZAO_SOCIAL, DS_NOME_CURTO FROM UNIMED_GYN.EMPRESA'

query_ped_ex_ext_item_hdata = 'SELECT NR_PROC_INTERNO, NR_SEQ_PEDIDO FROM UNIMED_GYN.PED_EX_EXT_IT'

query_ped_ex_ext_hdata = "SELECT NR_SEQUENCIA, NR_ATENDIMENTO, DT_INATIVACAO FROM UNIMED_GYN.PED_EX_EXT WHERE DT_INATIVACAO >= TO_DATE('{data_ini}', 'DD/MM/YYYY') AND DT_INATIVACAO < TO_DATE('{data_fim}', 'DD/MM/YYYY') + INTERVAL '1' DAY"

query_exame_lab_hdata = 'SELECT NR_SEQ_EXAME, NR_SEQ_GRUPO, NM_EXAME, DS_UNIDADE_MEDIDA FROM UNIMED_GYN.EXAME_LABORATORIO'

query_prescr_procedimento_hdata = 'SELECT IE_STATUS_ATEND, NR_SEQ_EXAME, NR_PRESCRICAO, CD_PROCEDIMENTO, IE_ORIGEM_PROCED, NR_SEQUENCIA, IE_VIA_APLICACAO, DS_HORARIOS, DS_JUSTIFICATIVA FROM UNIMED_GYN.PRESCR_PROCEDIMENTO'

query_prescr_medica_v_hdata = 'SELECT NR_PRESCRICAO, NR_ATENDIMENTO FROM UNIMED_GYN.PRESCR_MEDICA_V'

query_diagnostico_doenca_hdata = 'SELECT CD_DOENCA, NR_ATENDIMENTO, NR_SEQ_INTERNO FROM UNIMED_GYN.DIAGNOSTICO_DOENCA'

query_atendimento_paciente_hdata = "SELECT NR_ATENDIMENTO, NR_ATENDIMENTO_MAE, DT_ENTRADA, DT_INICIO_ATENDIMENTO, DT_ATEND_MEDICO, DT_ALTA, DT_ALTA_MEDICO, DT_FIM_TRIAGEM, NR_SEQ_TRIAGEM, DT_MEDICACAO, CD_MOTIVO_ALTA, CD_MOTIVO_ALTA_MEDICA, IE_TIPO_ATENDIMENTO, CD_PESSOA_FISICA, CD_MEDICO_RESP, NR_SEQ_PAC_SENHA_FILA, IE_CLINICA FROM UNIMED_GYN.ATENDIMENTO_PACIENTE WHERE DT_ENTRADA >= TO_DATE('{data_ini}', 'DD/MM/YYYY') AND DT_ENTRADA < TO_DATE('{data_fim}', 'DD/MM/YYYY') + INTERVAL '1' DAY"

query_atend_paciente_unidade_hdata = "SELECT NR_ATENDIMENTO, CD_SETOR_ATENDIMENTO, NR_SEQ_INTERNO, DT_ENTRADA_UNIDADE, DT_SAIDA_UNIDADE FROM UNIMED_GYN.ATEND_PAC_UNID WHERE DT_ENTRADA_UNIDADE >= TO_DATE('{data_ini}', 'DD/MM/YYYY') AND DT_ENTRADA_UNIDADE < TO_DATE('{data_fim}', 'DD/MM/YYYY') + INTERVAL '1' DAY"

query_setor_atendimento_hdata = 'SELECT DISTINCT CD_SETOR_ATENDIMENTO, DS_SETOR_ATENDIMENTO, CD_CLASSIF_SETOR FROM UNIMED_GYN.SETOR_ATENDIMENTO'

query_atend_categoria_convenio_hdata = "SELECT NR_ATENDIMENTO, CD_CONVENIO, NR_SEQ_INTERNO, CD_CATEGORIA, DT_INICIO_VIGENCIA FROM UNIMED_GYN.ATEND_CATEG_CONVENIO WHERE DT_INICIO_VIGENCIA >= TO_DATE('{data_ini}', 'DD/MM/YYYY') AND DT_INICIO_VIGENCIA < TO_DATE('{data_fim}', 'DD/MM/YYYY') + INTERVAL '1' DAY"

query_convenio_hdata = 'SELECT DISTINCT CD_CONVENIO, DS_CONVENIO FROM UNIMED_GYN.CONVENIO'

query_categoria_convenio_hdata = 'SELECT DISTINCT CD_CONVENIO, CD_CATEGORIA FROM UNIMED_GYN.CATEGORIA_CONVENIO'

query_pessoa_fisica_medico_hdata = "SELECT DISTINCT CD_PESSOA_FISICA, IE_SEXO, DT_CADASTRO_ORIGINAL, NM_PESSOA_PESQUISA FROM UNIMED_GYN.PESSOA_FISICA_MEDICO WHERE DT_CADASTRO_ORIGINAL >= TO_DATE('{data_ini}', 'DD/MM/YYYY') AND DT_CADASTRO_ORIGINAL < TO_DATE('{data_fim}', 'DD/MM/YYYY') + INTERVAL '1' DAY"

query_pessoa_fisica_pac_hdata = "SELECT DISTINCT CD_PESSOA_FISICA, DT_NASCIMENTO, IE_SEXO, DT_CADASTRO_ORIGINAL FROM UNIMED_GYN.PESSOA_FISICA_PAC WHERE DT_CADASTRO_ORIGINAL >= TO_DATE('{data_ini}', 'DD/MM/YYYY') AND DT_CADASTRO_ORIGINAL < TO_DATE('{data_fim}', 'DD/MM/YYYY') + INTERVAL '1' DAY"

query_pac_senha_fila_hdata = "SELECT DT_INICIO_ATENDIMENTO, DT_GERACAO_SENHA, DT_FIM_ATENDIMENTO, NR_SEQ_FILA_SENHA, NR_SEQUENCIA FROM UNIMED_GYN.PAC_SENHA_FILA WHERE DT_INICIO_ATENDIMENTO >= TO_DATE('{data_ini}', 'DD/MM/YYYY') AND DT_INICIO_ATENDIMENTO < TO_DATE('{data_fim}', 'DD/MM/YYYY') + INTERVAL '1' DAY"

query_motivo_alta_hdata = 'SELECT CD_MOTIVO_ALTA, DS_MOTIVO_ALTA FROM UNIMED_GYN.MOTIVO_ALTA'

query_valor_dominio_hdata = 'SELECT CD_DOMINIO, VL_DOMINIO, DS_VALOR_DOMINIO FROM UNIMED_GYN.VALOR_DOMINIO'

query_cid_doenca_hdata = 'SELECT CD_DOENCA_CID, DS_DOENCA_CID FROM UNIMED_GYN.CID_DOENCA'

query_triagem_classif_risco_hdata = 'SELECT NR_SEQUENCIA, DS_CLASSIFICACAO FROM UNIMED_GYN.TRIAGEM_CLASSIF_RISCO'

query_medico_especialidade_hdata = 'SELECT CD_PESSOA_FISICA, CD_ESPECIALIDADE FROM UNIMED_GYN.MEDICO_ESPECIALIDADE'

query_especialidade_medica_hdata = 'SELECT CD_ESPECIALIDADE, DS_ESPECIALIDADE FROM UNIMED_GYN.ESPECIALIDADE_MEDICA'